POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RhYWphIiwiaWQiOiI1ZjdkZjA4ZmEwMzA1MzYyZWJiYmU3YzgiLCJpYXQiOjE2MDIwODk0MTZ9.G0eZzCNlzg7T68Nt-iSR1_C5AqM7NW_ktQPL6wVMTr4

{
    "title": "Testiblogi",
    "author": "Tiina Testinen",
    "url": "testi.fi",
    "likes": 0
}